import { ProductDetail, ScannedProduct, MarketMetrics } from './MarketTypes';

export const MARKET_PRODUCTS: Record<string, ProductDetail> = {
  rice: {
    id: 'prod-rice',
    name: 'Basmati & Sona Masoori Bio-Rice',
    pricePerKg: 65,
    displayPrice: '₹65/kg',
    stock: '85% Available (1,450 kg)',
    stockStatus: 'Available',
    stockPercent: 85,
    origin: 'Vedic Eco-Farm Basin 4, Thanjavur Agro-Hub',
    organicStatus: '100% Certified Bio-Dynamic (Zero Synthetic Pesticides)',
    recommendation: 'Exceptional long-grain aroma, high prebiotic amylose content; best paired with organic heirloom lentils.',
    traceabilityHash: 'IOT-CROP-ETH-0x89A4F2',
    harvestDate: 'Fresh harvest: 3 days ago',
    nutritionalHighlights: ['Low GI Complex Carbs', 'Rich in Selenium & B6', 'Non-GMO Heritage Seed'],
  },
  tomato: {
    id: 'prod-tomato',
    name: 'Hydroponic Vine-Ripened Organic Tomatoes',
    pricePerKg: 40,
    displayPrice: '₹40/kg',
    stock: '92% Available (680 kg)',
    stockStatus: 'Available',
    stockPercent: 92,
    origin: 'Climate-Controlled Vertical Greenhouse Unit B',
    organicStatus: 'Certified Hydro-Organic (Nutrient Film Technique)',
    recommendation: 'Harvested at peak Brix sweetness (8.6); rich in lycopene antioxidant for cardiovascular health.',
    traceabilityHash: 'IOT-CROP-ETH-0x43C911',
    harvestDate: 'Harvested morning 06:15 AM',
    nutritionalHighlights: ['High Lycopene (8.2mg/100g)', 'Vitamin C Burst', 'Zero Cold-Storage Degradation'],
  },
  wheat: {
    id: 'prod-wheat',
    name: 'Whole Grain Golden Emmer Wheat (Khapli)',
    pricePerKg: 55,
    displayPrice: '₹55/kg',
    stock: '14% Low Stock (120 kg)',
    stockStatus: 'Low Stock',
    stockPercent: 14,
    origin: 'High-Altitude Solar Terrace Plots, Sub-Zone 3',
    organicStatus: 'Stone-Ground Unbleached Ancient Heirloom Grain',
    recommendation: 'Low glycemic load with easily digestible gluten profile; automated replenishment drone en route from silo 2.',
    traceabilityHash: 'IOT-CROP-ETH-0x21F88B',
    harvestDate: 'Direct Mill Batch #449',
    nutritionalHighlights: ['High Dietary Fiber (12.5g)', 'Naturally Polyphenol Rich', 'Low Gluten Allergenicity'],
  },
  vegetables: {
    id: 'prod-vegetables',
    name: 'Farm-Fresh Mixed Seasonal Greens & Crisp Vegetables',
    pricePerKg: 35,
    displayPrice: '₹35/kg',
    stock: '78% Available (940 kg)',
    stockStatus: 'Available',
    stockPercent: 78,
    origin: 'Aeroponic Vertical Tower Gardens, Zone A',
    organicStatus: 'Clean-Room Aeroponic Grade (Zero Soil Contaminants)',
    recommendation: 'Triple-misted with ultrasonic water fogger; high vitamin K & folate index for optimal cellular health.',
    traceabilityHash: 'IOT-CROP-ETH-0x76E00D',
    harvestDate: 'Continuous live harvest',
    nutritionalHighlights: ['Crisp Cell Integrity', 'Enzymatic Freshness Score 98.4%', 'Pure Mineral Irrigation'],
  },
};

export const SAMPLE_CHECKOUT_CART: ScannedProduct[] = [
  {
    id: 'cart-item-1',
    name: 'Organic Basmati Rice (2 kg)',
    category: 'Grains & Cereals',
    weightKg: 2,
    pricePerKg: 65,
    total: 130,
    rfidTag: 'RFID-RICE-092',
  },
  {
    id: 'cart-item-2',
    name: 'Hydroponic Vine Tomatoes (1.5 kg)',
    category: 'Fresh Produce',
    weightKg: 1.5,
    pricePerKg: 40,
    total: 60,
    rfidTag: 'RFID-TOM-118',
  },
  {
    id: 'cart-item-3',
    name: 'Crisp Seasonal Vegetables (1 kg)',
    category: 'Greens & Roots',
    weightKg: 1,
    pricePerKg: 35,
    total: 35,
    rfidTag: 'RFID-VEG-404',
  },
];

export const INITIAL_MARKET_METRICS: MarketMetrics = {
  customersToday: 1245,
  productsAvailable: 428,
  robotsActive: 8,
  avgScanSpeedMs: 38,
  organicCertificationRate: 100,
};
